import React, { useEffect, useState } from 'react';
import { LayoutV2 } from '../components';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '../lib/fontawesome';
import '../styles/globals.scss';
import Head from 'next/head';

config.autoAddCss = false;

function MyApp({ Component, pageProps }) {
  return (
    <LayoutV2>
      <Head>
				<title>Aman.Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

      <Component {...pageProps} />
    </LayoutV2>
  );
}

export default MyApp;
